# Generated by Django 5.0.6 on 2024-06-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'ShoppingCart', 'verbose_name_plural': 'ShoppingCarts'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcartitem',
            options={'verbose_name': 'ShoppingCartItem', 'verbose_name_plural': 'ShoppingCartItems'},
        ),
    ]
